env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 30

  position:
    x: 0
    y: 0

  decorations: full

  # startup_mode: Windowed
  startup_mode: Maximized
  # startup_mode: Fullscreen
  # startup_mode: SimpleFullscreen

scrolling:
  history: 10000

# tabspaces: 8

fonts:
  default: &default
    size: 20.0

  uni: &uni
    normal: {family: "S2G Uni font", style: Regular}
    bold: { family: "S2G Uni font", style: Regular }
    italic: { family: "S2G Uni font", style: Regular }
    size: 20
    offset: {x: 0, y: 0}

  uni_nerd: &uni_nerd
    normal: {family: "S2GUniFont Nerd Font", style: Regular}
    bold: { family: "S2GUniFont Nerd Font", style: Regular }
    italic: { family: "S2GUniFont Nerd Font", style: Regular }
    size: 22
    offset: {x: 0, y: 10}
    glyph_offset: {x: 0, y: 5}

  ricty: &ricty
    normal: {family: "Ricty Discord for Powerline", style: Regular}
    bold: { family: "Ricty Discord for Powerline", style: Bold }
    italic: { family: "Ricty Discord for Powerline", style: Oblique }
    size: 26
    offset: {x: 0, y: 10}

  moon: &moon
    normal: { family: "S2G Moon Font", style: Regular }
    bold: { family: "S2G Moon Font", style: Regular }
    italic: { family: "S2G Moon Font", style: Regular }
    size: 26
    offset: {x: 0, y: 15}

  luna: &luna
    normal: { family: "S2G Luna Font", style: Regular }
    bold: { family: "S2G Luna Font", style: Regular }
    italic: { family: "S2G Luna Font", style: Regular }
    size: 26
    offset: {x: 0, y: 15}

  sea: &sea
    normal: { family: "S2G Sea Font", style: Regular }
    bold: { family: "S2G Sea Font", style: Regular }
    italic: { family: "S2G Sea Font", style: Regular }
    size: 26
    offset: {x: 0, y: 15}

  jetbrains: &jetbrains
    normal: { family: "JetBrains Mono", style: "Regular" }
    bold: { family: "JetBrains Mono", style: "Bold" }
    italic: { family: "JetBrains Mono", style: "Italic" }
    size: 26.0
    offset: {x: 0, y: 7}

  sarasa: &sarasa
    normal: { family: "更紗等幅ゴシック J", style: Regular }
    bold: { family: "更紗等幅ゴシック J", style: Bold }
    italic: { family: "更紗等幅ゴシック J", style: Italic }
    size: 26.0
    offset: {x: 1, y: 2}

  sourcehan: &sourcehan
    normal: { family: "源ノ角ゴシック Code JP", style: N }
    bold: { family: "源ノ角ゴシック Code JP", style: B }
    italic: { family: "源ノ角ゴシック Code JP", style: N It }
    size: 26.0
    offset: {x: 0, y: 5}

  yutapon: &yutapon
    normal: { family: "ゆたぽん（コーディング）", style: Regular }
    bold: { family: "ゆたぽん（コーディング）Bold", style: Bold }
    italic: { family: "ゆたぽん（コーディング）Bold", style: Bold }
    size: 26.0
    offset: {x: 0, y: 15}

  yomogi: &yomogi
    normal: {family: "yomogi Nerd Font", style: Regular}
    bold: { family: "yomogi Nerd Font", style: Regular }
    italic: { family: "yomogi Nerd Font", style: Regular }
    size: 20
    offset: {x: 0, y: 0}

# `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
# !@#$%^&*()-_=
#
# +[]{}\|
# ;:'",./<>?

# font: *default
# font: *uni_nerd
# font: *ricty
# font: *moon
# font: *luna
# font: *sea
# font: *jetbrains
# font: *sarasa
# font: *sourcehan
# font: *yutapon
font: *yomogi

schemes:
  ayu-dark: &ayu-dark
    cursor:
      text: '0x1E222A'
      cursor: '0xF6CD76'

    selection:
      text: '0x2E323B'
      background: '0x171E29'

    primary:
      background: '0x0A0D13'
      foreground: '0xB2B1AD'

    # Normal colors
    normal:
      black:   '0x02050c'
      red:     '0xe0787a'
      green:   '0xc6d863'
      yellow:  '0xf3b765'
      blue:    '0x75bff9'
      magenta: '0xfceea3'
      cyan:    '0xa7e3cc'
      white:   '0xc7c7c7'

    # Bright colors
    bright:
      black:   '0xc7c7c7'
      red:     '0xff3333'
      green:   '0xc2d94c'
      yellow:  '0xe7c547'
      blue:    '0x59c2ff'
      magenta: '0xb77ee0'
      cyan:    '0x5ccfe6'
      white:   '0xffffff'

  ayu-mirage: &ayu-mirage
    primary:
      # background: '0x243742'
      background: '0x1f2430'
      foreground: '0xabb2bf'

    cursor:
      text: '0x373E4C'
      cursor: '0xFFCC66'

    selection:
      text: '0x586071'
      background: '0x2A3546'

    # Normal colors
    normal:
      black: '0x1A1E29'
      red: '0xF28779'
      green: '0xBAE67E'
      yellow: '0xFFD580'
      blue: '0x73D0FF'
      magenta: '0xD4BFFF'
      cyan: '0x95E6CB'
      white: '0xC7C7C7'

    # Bright colors
    bright:
      black: '0x686868'
      red: '0xF28779'
      green: '0xBAE67E'
      yellow: '0xFFD580'
      blue: '0x73D0FF'
      magenta: '0xD4BFFF'
      cyan: '0x95E6CB'
      white: '0xFFFFFF'

  ayu-light: &ayu-light
    primary:
      background: '0xfafafa'
      foreground: '0x5b6672'

    # Normal colors
    normal:
      black: '0x000000' #0
      red: '0xf2590b' #1
      green: '0x76cc00' #2
      yellow: '0xf29717' #3
      blue: '0x41a5d9' #4
      magenta: '0x9965cc' #5
      cyan: '0x4dbf98' #6
      white: '0xc7c7c7' #7

    # Bright colors
    bright:
      black: '0x676767'
      red: '0xd6646a' #9
      green: '0xa3d900' #10
      yellow: '0xe7c446' #11
      blue: '0x6871ff' #12
      magenta: '0xa37acc' #13
      cyan: '0x56d9ad' #14
      white: '0xfeffff' #15

  palenight: &palenight
    primary:
      background: '0x292d3e'
      foreground: '0x959dcb'

    cursor:
      text: '0x292d3e'
      cursor: '0x959dcb'

    normal:
      black:   '0x292d3e'
      red:     '0xf07178'
      green:   '0xc3e88d'
      yellow:  '0xffcb6b'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x89ddff'
      white:   '0x959dcb'

    bright:
      black:   '0x676e95'
      red:     '0xf78c6c'
      green:   '0x444267'
      yellow:  '0x32374d'
      blue:    '0x8796b0'
      magenta: '0x959dcb'
      cyan:    '0xff5370'
      white:   '0xffffff'

  sonokai: &sonokai
    primary:
      background: "0x2c2e34"
      foreground: "0xe2e2e3"

    normal:
      black: "0x181819"
      red: "0xfc5d7c"
      green: "0x9ed072"
      yellow: "0xe7c664"
      blue: "0x76cce0"
      magenta: "0xb39df3"
      cyan: "0xf39660"
      white: "0xe2e2e3"

    bright:
      black: "0x7f8490"
      red: "0xfc5d7c"
      green: "0x9ed072"
      yellow: "0xe7c664"
      blue: "0x76cce0"
      magenta: "0xb39df3"
      cyan: "0xf39660"
      white: "0xe2e2e3"

colors: *ayu-dark
# colors: *ayu-light
# colors: *palenight

draw_bold_text_with_bright_colors: true

selection:
  # semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
dynamic_title: true

cursor:
  # style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

# shell:
#   program: "zsh"
#   args:
#     - -l
#     - -c
#     - "tmux a -t $(basename ~ | perl -pe 's/\\./_/g') || tmux new -s $(basename ~ | perl -pe 's/\\./_/g')"

# shell:
#   program: 'C:\Windows\system32\wsl.exe'

working_directory: None

# Send ESC (\x1b) before characters when alt is pressed.
# alt_send_esc: true

hints:
  enabled:
    - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Control

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true


# Key bindings
#
# Key bindings are specified as a list of objects. For example, this is the
# default paste binding:
#
# `- { key: V, mods: Control|Shift, action: Paste }`
#
# Each key binding will specify a:
#
# - `key`: Identifier of the key pressed
#
#    - A-Z
#    - F1-F24
#    - Key0-Key9
#
#    A full list with available key codes can be found here:
#    https://docs.rs/glutin/*/glutin/event/enum.VirtualKeyCode.html#variants
#
#    Instead of using the name of the keys, the `key` field also supports using
#    the scancode of the desired key. Scancodes have to be specified as a
#    decimal number. This command will allow you to display the hex scancodes
#    for certain keys:
#
#       `showkey --scancodes`.
#
# Then exactly one of:
#
# - `chars`: Send a byte sequence to the running application
#
#    The `chars` field writes the specified string to the terminal. This makes
#    it possible to pass escape sequences. To find escape codes for bindings
#    like `PageUp` (`"\x1b[5~"`), you can run the command `showkey -a` outside
#    of tmux. Note that applications use terminfo to map escape sequences back
#    to keys. It is therefore required to update the terminfo when changing an
#    escape sequence.
#
# - `action`: Execute a predefined action
#
#   - Copy
#   - Paste
#   - PasteSelection
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollLineUp
#   - ScrollLineDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#   - Hide
#   - Quit
#   - ToggleFullscreen
#   - SpawnNewInstance
#   - ClearLogNotice
#   - ReceiveChar
#   - None
#
#   (macOS only):
#   - ToggleSimpleFullscreen: Enters fullscreen without occupying another space
#
# - `command`: Fork and execute a specified command plus arguments
#
#    The `command` field must be a map containing a `program` string and an
#    `args` array of command line parameter strings. For example:
#       `{ program: "alacritty", args: ["-e", "vttest"] }`
#
# And optionally:
#
# - `mods`: Key modifiers to filter binding actions
#
#    - Command
#    - Control
#    - Option
#    - Super
#    - Shift
#    - Alt
#
#    Multiple `mods` can be combined using `|` like this:
#       `mods: Control|Shift`.
#    Whitespace and capitalization are relevant and must match the example.
#
# - `mode`: Indicate a binding for only specific terminal reported modes
#
#    This is mainly used to send applications the correct escape sequences
#    when in different modes.
#
#    - AppCursor
#    - AppKeypad
#    - Alt
#
#    A `~` operator can be used before a mode to apply the binding whenever
#    the mode is *not* active, e.g. `~Alt`.
#
# Bindings are always filled by default, but will be replaced when a new
# binding with the same triggers is defined. To unset a default binding, it can
# be mapped to the `ReceiveChar` action. Alternatively, you can use `None` for
# a no-op if you do not wish to receive input characters for that binding.
key_bindings:

  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }

  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }

  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                   }

  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }

  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: B,        mods: Control, chars: "\x1bOD",   mode: ~AppCursor   }
  - { key: B,        mods: Control, chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: F,        mods: Control, chars: "\x1bOC",   mode: ~AppCursor   }
  - { key: F,        mods: Control, chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  # - { key: P,        mods: Control, chars: "\x1b[A",   mode: ~AppCursor  }
  # - { key: P,        mods: Control, chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  # - { key: N,        mods: Control, chars: "\x1b[B",   mode: ~AppCursor  }
  # - { key: N,        mods: Control, chars: "\x1bOB",   mode: AppCursor   }

  # (Windows/Linux only)
  #- { key: V,        mods: Control|Shift, action: Paste            }
  #- { key: C,        mods: Control|Shift, action: Copy             }
  #- { key: Insert,   mods: Shift,         action: PasteSelection   }
  #- { key: Key0,     mods: Control,       action: ResetFontSize    }
  #- { key: Equals,   mods: Control,       action: IncreaseFontSize }
  #- { key: Subtract, mods: Control,       action: DecreaseFontSize }
  #- { key: Minus,    mods: Control,       action: DecreaseFontSize }
  #- { key: Return,   mods: Alt,           action: ToggleFullscreen }

  - { key: Q,      mods: Control,         chars: "\x11" }

  # (macOS only)
  - { key: Key0,   mods: Command,         action: ResetFontSize          }
  - { key: Equals, mods: Command,         action: IncreaseFontSize       }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize       }
  - { key: K,      mods: Command,         action: ClearHistory           }
  - { key: V,      mods: Command,         action: Paste                  }
  - { key: C,      mods: Command,         action: Copy                   }
  - { key: Q,      mods: Command,         action: Quit                   }
  - { key: W,      mods: Command,         action: Quit                   }
  # - { key: F,      mods: Command,         action: ToggleSimpleFullscreen }
  - { key: N,      mods: Command,         action: SpawnNewInstance       }

  # - { key: Paste,                    action: Paste                            }
  # - { key: Copy,                     action: Copy                             }
  # - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  # - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  # - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  # - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }

  - {key: A, mods: Alt, chars: "\x1ba"}
  - {key: B, mods: Alt, chars: "\x1bb"}
  - {key: C, mods: Alt, chars: "\x1bc"}
  - {key: D, mods: Alt, chars: "\x1bd"}
  - {key: E, mods: Alt, chars: "\x1be"}
  - {key: F, mods: Alt, chars: "\x1bf"}
  - {key: G, mods: Alt, chars: "\x1bg"}
  - {key: H, mods: Alt, chars: "\x1bh"}
  - {key: I, mods: Alt, chars: "\x1bi"}
  - {key: J, mods: Alt, chars: "\x1bj"}
  - {key: K, mods: Alt, chars: "\x1bk"}
  - {key: L, mods: Alt, chars: "\x1bl"}
  - {key: M, mods: Alt, chars: "\x1bm"}
  - {key: N, mods: Alt, chars: "\x1bn"}
  - {key: O, mods: Alt, chars: "\x1bo"}
  - {key: P, mods: Alt, chars: "\x1bp"}
  - {key: Q, mods: Alt, chars: "\x1bq"}
  - {key: R, mods: Alt, chars: "\x1br"}
  - {key: S, mods: Alt, chars: "\x1bs"}
  - {key: T, mods: Alt, chars: "\x1bt"}
  - {key: U, mods: Alt, chars: "\x1bu"}
  - {key: V, mods: Alt, chars: "\x1bv"}
  - {key: W, mods: Alt, chars: "\x1bw"}
  - {key: X, mods: Alt, chars: "\x1bx"}
  - {key: Y, mods: Alt, chars: "\x1by"}
  - {key: Z, mods: Alt, chars: "\x1bz"}
