[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'


#
# development:general
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# [[plugins]]
# repo = 'lambdalisue/fern.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'vim-scripts/catn.vim'
# [[plugins]]
# repo = 'tyru/caw.vim'
[[plugins]]
repo = 'tpope/vim-commentary'
# [[plugins]]
# repo = 'preservim/nerdcommenter'
# [[plugins]]
# repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'machakann/vim-sandwich'
[[plugins]]
repo = 'deton/jasegment.vim'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tmhedberg/matchit'
# [[plugins]]
# repo = 'itchyny/vim-parenmatch'
[[plugins]]
repo = 'leafOfTree/vim-matchtag'
[[plugins]]
repo = 'deris/vim-rengbang'
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
[[plugins]]
repo = 'kana/vim-smartinput'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'reireias/vim-cheatsheet'
[[plugins]]
repo = 'glidenote/memolist.vim'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
# [[plugins]]
# repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
[[plugins]]
repo = 'liuchengxu/vista.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
[[plugins]]
repo = 't9md/vim-choosewin'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'osyo-manga/vim-over'
[[plugins]]
repo = 'syui/airsave.vim'
[[plugins]]
repo = 'terryma/vim-expand-region'


# git
[[plugins]]
repo = 'tpope/vim-fugitive'
# git logDefx
[[plugins]]
repo = 'cohama/agit.vim'
# git branch管理
[[plugins]]
repo = 'idanarye/vim-merginal'
# git commit
[[plugins]]
repo = 'rhysd/committia.vim'
# git 差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
# git blame
[[plugins]]
repo = 'APZelos/blamer.nvim'


#
# textobj
# https://github.com/kana/vim-textobj-user/wiki
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-line' # al
[[plugins]]
repo = 'kana/vim-textobj-entire' # ae
[[plugins]]
repo = 'kana/vim-textobj-function' #af / aF
[[plugins]]
repo = 'kana/vim-textobj-indent' # ai / aI
[[plugins]]
repo = 'kana/vim-textobj-jabraces' # aj{X}
[[plugins]]
repo = 'thinca/vim-textobj-comment' # ac
[[plugins]]
repo = 'lucapette/vim-textobj-underscore' #a_
[[plugins]]
repo = 'sgur/vim-textobj-parameter' #a,
[[plugins]]
repo = 'machakann/vim-textobj-delimited'  #ad aD
[[plugins]]
repo = 'pocke/vim-textobj-markdown' #c
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock' #sb
[[plugins]]
repo = 'github/copilot.vim'
[[plugins]]
repo = 'mattn/vim-chatgpt'


# language server client
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'


#
# filetype
[[plugins]]
repo='docteurklein/vim-symfony'
on_ft = ["php"]
[[plugins]]
repo='stephpy/vim-php-cs-fixer'
on_ft = ["php"]
[[plugins]]
repo = 'kmyk/brainfuck-highlight.vim'
on_ft = ["bf"]
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ["ps1"]
[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ["csv"]
[[plugins]]
repo = 'vim-scripts/applescript.vim'
on_ft = ["applescript"]
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ["graphql"]
# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# [[plugins]]
# repo = 'stephpy/vim-yaml'
# [[plugins]]
# repo = 'cespare/vim-toml'
# [[plugins]]
# repo = 'neoclide/jsonc.vim'
# on_ft = ["jsonc"]
# [[plugins]]
# repo='vim-scripts/php-annotations-syntax'
# on_ft = ["php"]
# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
# on_ft = ["scss"]
# [[plugins]]
# repo = 'billyvg/tigris.nvim'
# on_ft = ['javascript', 'typescript', 'vue']
# hook_post_update = '''
#   let g:dein#plugin.build = './install.sh'
# '''
# [[plugins]]
# repo = "leafgarland/typescript-vim"
# on_ft = ["javascript, typescript"]
# [[plugins]]
# repo = "evanleck/vim-svelte"
# on_ft = ["svelte"]
# [[plugins]]
# repo = 'tbastos/vim-lua'
# on_ft = ["lua"]
# [[plugins]]
# repo = 'rust-lang/rust.vim'
# on_ft = ["rust"]
# [[plugins]]
# repo = 'mhinz/vim-crates'
# on_ft = ["toml"]
# repo = 'neovimhaskell/haskell-vim'
# on_ft = ["hs"]
# こいつらonにすると重い
# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ["javascript, typescript"]
# [[plugins]]
# repo = 'othree/es.next.syntax.vim'
# on_ft = ["javascript, typescript"]
# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
# on_ft = ["javascript, typescript"]

# markdown
[[plugins]]
repo = 'preservim/vim-markdown'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
[[plugins]]
repo = 'mattn/vim-maketable'
[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
# [[plugins]]
# repo = 'iamcco/markdown-preview.nvim'
# on_ft = ['markdown', 'pandoc.markdown', 'rmd']
# build = 'cd app & yarn install'
[[plugins]]
repo = 'previm/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'vim-scripts/VOoM'
[[plugins]]
repo = 'habamax/vim-asciidoctor'


# syntax
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
[[plugins]]
repo = 'RRethy/nvim-treesitter-endwise'
[[plugins]]
repo = 'kat0h/vim-auto-color-switcher'
hook_post_update = '''
let g:dein#plugin.build = 'make'
'''

# [[plugins]]
# repo = 'Shatur/neovim-ayu'
# [[plugins]]
# repo = 'Th3Whit3Wolf/one-nvim'
# [[plugins]]
# repo = 'olimorris/onedarkpro.nvim'
# [[plugins]]
# repo = 'tanvirtin/monokai.nvim'
[[plugins]]
repo = 'sainnhe/sonokai'
[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
[[plugins]]
repo = 'Th3Whit3Wolf/onebuddy'
[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo = 'marko-cerovac/material.nvim'
# [[plugins]]
# repo = 'sainnhe/everforest'
# [[plugins]]
# repo = 'sainnhe/edge'
# [[plugins]]
# repo = 'tiagovla/tokyodark.nvim'
# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# [[plugins]]
# repo = 'EdenEast/nightfox.nvim'


[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'thinca/vim-scouter'

