-- vim.opt.foldmethod     = 'expr'
-- vim.opt.foldexpr       = 'nvim_treesitter#foldexpr()'
---WORKAROUND
-- vim.api.nvim_create_autocmd({'BufEnter','BufAdd','BufNew','BufNewFile','BufWinEnter'}, {
--   group = vim.api.nvim_create_augroup('TS_FOLD_WORKAROUND', {}),
--   callback = function()
--     vim.opt.foldmethod     = 'expr'
--     vim.opt.foldexpr       = 'nvim_treesitter#foldexpr()'
--   end
-- })

require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    -- "ada",
    -- "agda",
    -- "arduino",
    -- "astro",
    "awk",
    "bash",
    -- "beancount",
    -- "bibtex",
    -- "blueprint",
    -- "c",
    -- "c_sharp",
    -- "capnp",
    -- "chatito",
    -- "clojure",
    -- "cmake",
    "comment",
    "commonlisp",
    -- "cooklang",
    -- "cpp",
    "css",
    -- "cuda",
    -- "d",
    -- "dart",
    -- "devicetree",
    "diff",
    "dockerfile",
    -- "dot",
    -- "ebnf",
    -- "eex",
    -- "elixir",
    -- "elm",
    -- "elsa",
    -- "elvish",
    -- "embedded_template",
    -- "erlang",
    -- "fennel",
    -- "fish",
    -- "foam",
    -- "fortran",
    -- "fsh",
    -- "func",
    -- "fusion",
    -- "Godot",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    -- "gleam",
    -- "GlimmerandEmber",
    -- "glsl",
    "go",
    -- "GodotResources",
    -- "gomod",
    -- "gosum",
    -- "gowork",
    "graphql",
    -- "hack",
    "haskell",
    -- "hcl",
    -- "heex",
    -- "help",
    -- "hjson",
    -- "hlsl",
    -- "hocon",
    "html",
    -- "htmldjango",
    "http",
    "ini",
    -- "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    -- "jsonnet",
    -- "julia",
    -- "kdl",
    -- "kotlin",
    -- "lalrpop",
    -- "latex",
    -- "ledger",
    -- "llvm",
    "lua",
    -- "m68k",
    -- "make",
    "markdown",
    "markdown_inline",
    -- "menhir",
    "mermaid",
    "meson",
    -- "nickel",
    -- "ninja",
    -- "nix",
    -- "norg",
    -- "ocaml",
    -- "ocaml_interface",
    -- "ocamllex",
    -- "org",
    -- "pascal",
    "perl",
    "php",
    "phpdoc",
    -- "pioasm",
    -- "PathofExileitemfilter",
    -- "prisma",
    -- "proto",
    -- "pug",
    "python",
    -- "ql",
    -- "qmljs",
    -- "tree-sitter-query",
    -- "r",
    -- "racket",
    -- "rasi",
    "regex",
    -- "rego",
    -- "rnoweb",
    -- "ron",
    -- "rst",
    "ruby",
    "rust",
    -- "scala",
    -- "scheme",
    "scss",
    -- "slint",
    -- "smali",
    -- "smithy",
    -- "solidity",
    -- "sparql",
    "sql",
    -- "supercollider",
    -- "surface",
    "svelte",
    -- "swift",
    -- "sxhkdrc",
    -- "t32",
    -- "teal",
    -- "terraform",
    -- "thrift",
    -- "tiger",
    -- "tlaplus",
    "todotxt",
    "toml",
    "tsx",
    -- "turtle",
    -- "twig",
    "typescript",
    -- "v",
    -- "vala",
    -- "verilog",
    -- "vhs",
    "vim",
    "vue",
    -- "wgsl",
    -- "wgsl_bevy",
    "yaml",
    -- "yang",
    -- "zig",
  },
  highlight = {
    enable = true,
  },
  indent = {
    enable = true
    -- enable = false,
  },
  endwise = {
    enable = true
  },
  context_commentstring = {
    enable = true
  },
}
---ENDWORKAROUND
